import feature1 from "@/public/feature1.webp";
import feature2 from "@/public/feature2.webp";
import feature3 from "@/public/feature3.webp";
import youtube from "@/public/youtube_logo.svg";
import slack from "@/public/slack_logo.svg";
import instagram from "@/public/instagram_logo.svg";
import x from "@/public/x_logo.svg";
import person1 from "@/public/person1.webp";
import person2 from "@/public/person2.webp";
import person3 from "@/public/person3.webp";
import person4 from "@/public/person4.webp";
import person5 from "@/public/person5.webp";

export const featureItems = [
  {
    imgUrl: feature1,
    title: "We bring you Recipies from all around the globe.",
    desc: "We put all of our heart and soul into bringing you the best spicy meals this world has to offer to satisfy you chilly loving tastebuds through unique menus every week so that you'll never run out of options.",
  },
  {
    imgUrl: feature2,
    title: "Only the spiciest delicacies to lit you tastebuds on FIRE.",
    desc: "Every meal you recieve is handpicked from different parts of the world and is checked by our experts to ensure the every bite packs a fiery punch of flavours in you mouth.",
  },
  {
    imgUrl: feature3,
    title: "Fresh & Quality checked raw materials only.",
    desc: "A good meal always starts with fresh and quality raw materials. We provide you with healthy and quality checked raw materials to make sure you're getting the best out of every meal.",
  },
];

export const footerLinks = [
  {
    title: "Navigation",
    links: [
      { name: "Home", url: "/" },
      { name: "Menu", url: "/menu" },
    ],
  },
  {
    title: "Other Links",
    links: [
      { name: "FAQs", url: "/faqs" },
      { name: "Our Ingredients", url: "/ingredients-lists" },
      { name: "Gift Cards", url: "/gift-cards" },
    ],
  },
  {
    title: "Term & Conditions",
    links: [
      { name: "Press", url: "/press" },
      { name: "Terms of Use", url: "/terms-of-use" },
      { name: "Purchase Terms & Conditions", url: "/purchase-terms" },
    ],
  },
];

export const socialMedia = [
  { name: "YouTube", icon: youtube },
  { name: "Slack", icon: slack },
  { name: "Instagram", icon: instagram },
  { name: "X", icon: x },
];

export const dummyReviews = [
  {
    userName: "User 1",
    reviewTitle: "Great Experience",
    rating: 5,
    imgUrl: person1,
    reviewDescription:
      "Had a wonderful experience at this place. Highly recommended.",
  },
  {
    userName: "User 2",
    reviewTitle: "Good Service",
    rating: 4,
    imgUrl: person2,
    reviewDescription:
      "The service was excellent, and the staff was very friendly.",
  },
  {
    userName: "User 3",
    reviewTitle: "Average",
    rating: 3,
    imgUrl: person3,
    reviewDescription: "The experience was just okay. It could be better.",
  },
  {
    userName: "User 4",
    reviewTitle: "Not Recommended",
    rating: 1,
    imgUrl: person4,
    reviewDescription: "I would not recommend this place. Bad experience.",
  },
  {
    userName: "User 5",
    reviewTitle: "Excellent Food",
    rating: 5,
    imgUrl: person5,
    reviewDescription: "The food here is amazing. Will definitely come back.",
  },
];

export const meals = [
  {
    title: "Sautéed Ground Pork over Jasmine Rice",
    ingredients:
      "Toasted Peanuts & Quick-Pickled Cucumber SaladToasted Peanuts & Quick-Pickled Cucumber Salad",
    description: "Gingery pork, crunchy cucumbers, and toasty peanuts",
    category: "Lunch",
    price: 19.99,
    cookingTime: 25,
    servings: 2,
    imageUrl: "Sautéed_Ground_Pork_over_Jasmine_Rice.webp",
    topMeal: false,
  },
  {
    title: "French Toast",
    ingredients: "Bread slices, eggs, milk, cinnamon, syrup",
    description: "Crispy French toast with a hint of cinnamon and syrup",
    category: "Breakfast",
    price: 5.99,
    cookingTime: 15,
    servings: 2,
    imageUrl: "French_Toast.webp",
    topMeal: true,
  },
  {
    title: "Grilled Shrimp",
    ingredients:
      "Garlic Cloves, Italian Seasoning, Dijon mustard & Lemon Juice",
    description: "With chopped parsley",
    category: "Dinner",
    price: 23.99,
    cookingTime: 35,
    servings: 1,
    imageUrl: "Grilled_Shrimp.webp",
    topMeal: false,
  },
  {
    title: "Chilly Chicken",
    ingredients: "Chicken, Bell Peppers, Garlic, Chilli and Soya Sauce",
    description: "With roasted chilly and veggies",
    category: "Lunch",
    price: 19.99,
    cookingTime: 25,
    servings: 2,
    imageUrl: "Chilly_Chicken.webp",
    topMeal: true,
  },
  {
    title: "Spicy Spaghetti",
    ingredients:
      "Pasta, Olive Oil, Cherry Tomatoes, Chilli Peppers, Herbs and Spices",
    description: "Italian cuisine",
    category: "Lunch",
    price: 20.99,
    cookingTime: 15,
    servings: 3,
    imageUrl: "Spicy_Spaghetti.webp",
    topMeal: false,
  },
  {
    title: "Black Bean Tostadas",
    ingredients: "Corn Salsa, Avocado Ranch, Pickled Red Onions",
    description: "With avocado and corn salsa",
    category: "Lunch",
    price: 19.99,
    cookingTime: 25,
    servings: 2,
    imageUrl: "Black_Bean_Tostadas.webp",
    topMeal: false,
  },
  {
    title: "Arroz Con Pollo",
    ingredients:
      "Freshly ground black pepper, ground cumin, onion, bell peppers, garlic cloves",
    description: "low-sodium chicken, with diced onions and cilantro",
    category: "Dinner",
    price: 15.99,
    cookingTime: 15,
    servings: 2,
    imageUrl: "Arroz_Con_Pollo.webp",
    topMeal: false,
  },
  {
    title: "Chicken Alfredo",
    ingredients:
      "Fettuccine pasta, chicken breast, Alfredo sauce, garlic, Parmesan cheese",
    description: "Creamy Alfredo pasta with grilled chicken",
    category: "Dinner",
    price: 17.99,
    cookingTime: 30,
    servings: 2,
    imageUrl: "Chicken_Alfredo.webp",
    topMeal: true,
  },
  {
    title: "Mango Salsa Salmon",
    ingredients: "Salmon fillet, mango salsa, lime juice, cilantro",
    description: "Grilled salmon with fresh mango salsa",
    category: "Dinner",
    price: 22.99,
    cookingTime: 20,
    servings: 2,
    imageUrl: "Mango_Salsa_Salmon.webp",
    topMeal: true,
  },
  {
    title: "Caprese Salad",
    ingredients: "Tomatoes, fresh mozzarella, basil leaves, balsamic glaze",
    description: "Classic Italian salad with a balsamic twist",
    category: "Lunch",
    price: 14.99,
    cookingTime: 10,
    servings: 2,
    imageUrl: "Caprese_Salad.webp",
    topMeal: false,
  },
  {
    title: "Vegetable Stir-Fry",
    ingredients: "Assorted vegetables, tofu, soy sauce, ginger, garlic",
    description: "Healthy and delicious vegetable stir-fry",
    category: "Lunch",
    price: 16.99,
    cookingTime: 20,
    servings: 3,
    imageUrl: "Vegetable_Stir-Fry.webp",
    topMeal: false,
  },
  {
    title: "Beef Tacos",
    ingredients:
      "Ground beef, taco seasoning, tortillas, lettuce, cheese, salsa",
    description: "Tasty and spicy beef tacos",
    category: "Dinner",
    price: 15.99,
    cookingTime: 25,
    servings: 3,
    imageUrl: "Beef_Tacos.webp",
    topMeal: false,
  },
  {
    title: "Penne alla Vodka",
    ingredients:
      "Penne pasta, vodka sauce, heavy cream, Parmesan cheese, red pepper flakes",
    description: "Creamy and slightly spicy penne pasta",
    category: "Dinner",
    price: 18.99,
    cookingTime: 35,
    servings: 2,
    imageUrl: "Penne_alla_Vodka.webp",
    topMeal: false,
  },
  {
    title: "Lobster Bisque",
    ingredients: "Lobster meat, heavy cream, butter, sherry, garlic, thyme",
    description: "Rich and creamy lobster bisque",
    category: "Specials",
    price: 25.99,
    cookingTime: 40,
    servings: 2,
    imageUrl: "Lobster_Bisque.webp",
    topMeal: true,
  },
  {
    title: "Mushroom Risotto",
    ingredients:
      "Arborio rice, mushrooms, shallots, white wine, Parmesan cheese",
    description: "Creamy mushroom risotto with a hint of white wine",
    category: "Specials",
    price: 19.99,
    cookingTime: 40,
    servings: 2,
    imageUrl: "Mushroom_Risotto.webp",
    topMeal: true,
  },
  {
    title: "Eggplant Parmesan",
    ingredients: "Sliced eggplant, marinara sauce, mozzarella cheese, basil",
    description:
      "Delicious layers of eggplant with marinara sauce and melted mozzarella cheese",
    category: "Specials",
    price: 20.99,
    cookingTime: 45,
    servings: 2,
    imageUrl: "Eggplant_Parmesan.webp",
    topMeal: false,
  },
  {
    title: "Breakfast Burrito",
    ingredients: "Eggs, sausage, cheese, bell peppers, tortilla",
    description: "Scrambled eggs, sausage, and cheese wrapped in a tortilla",
    category: "Breakfast",
    price: 6.99,
    cookingTime: 20,
    servings: 1,
    imageUrl: "Breakfast_Burrito.webp",
    topMeal: false,
  },
  {
    title: "Pancakes and Bacon",
    ingredients: "Pancake mix, bacon strips, maple syrup",
    description: "Fluffy pancakes with crispy bacon and maple syrup",
    category: "Breakfast",
    price: 8.99,
    cookingTime: 25,
    servings: 2,
    imageUrl: "Pancakes_and_Bacon.webp",
    topMeal: false,
  },
  {
    title: "Veggie Omelette",
    ingredients: "Eggs, bell peppers, onions, tomatoes, cheese",
    description: "Omelette filled with fresh vegetables and cheese",
    category: "Breakfast",
    price: 7.99,
    cookingTime: 15,
    servings: 1,
    imageUrl: "Veggie_Omelette.webp",
    topMeal: false,
  },
  {
    title: "Greek Yogurt Parfait",
    ingredients: "Greek yogurt, granola, mixed berries, honey",
    description:
      "Creamy Greek yogurt with crunchy granola, fresh berries, and honey",
    category: "Breakfast",
    price: 4.99,
    cookingTime: 5,
    servings: 1,
    imageUrl: "Greek_Yogurt_Parfait.webp",
    topMeal: false,
  },
];

export const ontarioCities = [
  { id: 1, name: 'Ajax' },
  { id: 2, name: 'Amherstburg' },
  { id: 3, name: 'Arnprior' },
  { id: 4, name: 'Aurora' },
  { id: 5, name: 'Barrie' },
  { id: 6, name: 'Belleville' },
  { id: 7, name: 'Bracebridge' },
  { id: 8, name: 'Bradford West Gwillimbury' },
  { id: 9, name: 'Brampton' },
  { id: 10, name: 'Brant (incl. Paris)' },
  { id: 11, name: 'Brantford' },
  { id: 12, name: 'Brockville' },
  { id: 13, name: 'Burlington' },
  { id: 14, name: 'Caledon (incl. Bolton)' },
  { id: 15, name: 'Cambridge' },
  { id: 16, name: 'Carleton Place' },
  { id: 17, name: 'Chatham - Kent' },
  { id: 18, name: 'Clarence-Rockland' },
  { id: 19, name: 'Clarington (incl. Bowmanville, Newcastle)' },
  { id: 20, name: 'Cobourg' },
  { id: 21, name: 'Collingwood' },
  { id: 22, name: 'Cornwall' },
  { id: 23, name: 'East Gwillimbury (incl. Holland Landing, Sharon)' },
  { id: 24, name: 'Elliot Lake' },
  { id: 25, name: 'Erin' },
  { id: 26, name: 'Essex' },
  { id: 27, name: 'Fort Erie' },
  { id: 28, name: 'Georgina (incl. Keswick)' },
  { id: 29, name: 'Gravenhurst' },
  { id: 30, name: 'Greater Napanee (incl. Napanee)' },
  { id: 31, name: 'Greater Sudbury (Grand Sudbury)' },
  { id: 32, name: 'Grimsby' },
  { id: 33, name: 'Guelph' },
  { id: 34, name: 'Haldimand County (incl. Cayuga, Caledonia, Hagersville)' },
  { id: 35, name: 'Halton Hills (incl. Acton, Georgetown)' },
  { id: 36, name: 'Hamilton' },
  { id: 37, name: 'Hawkesbury' },
  { id: 38, name: 'Huntsville' },
  { id: 39, name: 'Ingersoll' },
  { id: 40, name: 'Innisfil' },
  { id: 41, name: 'Kawartha Lakes (incl. Lindsay)' },
  { id: 42, name: 'Kenora' },
  { id: 43, name: 'Kingston' },
  { id: 44, name: 'Kingsville' },
  { id: 45, name: 'Kitchener' },
  { id: 46, name: 'Lakeshore (incl. Belle River, Tilbury)' },
  { id: 47, name: 'LaSalle' },
  { id: 48, name: 'Leamington' },
  { id: 49, name: 'Lincoln (incl. Beamsville)' },
  { id: 50, name: 'London' },
  { id: 51, name: 'Markham' },
  { id: 52, name: 'Midland' },
  { id: 53, name: 'Milton' },
  { id: 54, name: 'Mississauga' },
  { id: 55, name: 'Mississippi Mills (incl. Almonte)' },
  { id: 56, name: 'Mono' },
  { id: 57, name: 'Newmarket' },
  { id: 58, name: 'New Tecumseth (incl. Alliston)' },
  { id: 59, name: 'Niagara Falls' },
  { id: 60, name: 'Niagara-on-the-Lake' },
  { id: 61, name: 'Norfolk County (incl. Simcoe)' },
  { id: 62, name: 'North Bay' },
  { id: 63, name: 'Oakville' },
  { id: 64, name: 'Orangeville' },
  { id: 65, name: 'Orillia' },
  { id: 66, name: 'Oshawa' },
  { id: 67, name: 'Ottawa' },
  { id: 68, name: 'Owen Sound' },
  { id: 69, name: 'Pelham' },
  { id: 70, name: 'Pembroke' },
  { id: 71, name: 'Penetanguishene' },
  { id: 72, name: 'Petawawa' },
  { id: 73, name: 'Peterborough' },
  { id: 74, name: 'Pickering' },
  { id: 75, name: 'Port Colborne' },
  { id: 76, name: 'Port Hope' },
  { id: 77, name: 'Prince Edward County (incl. Picton)' },
  { id: 78, name: 'Quinte West (incl. Trenton)' },
  { id: 79, name: 'Richmond Hill' },
  { id: 80, name: 'Sarnia' },
  { id: 81, name: 'Saugeen Shores (incl. Port Elgin, Southampton)' },
  { id: 82, name: 'Sault Ste. Marie' },
  { id: 83, name: 'Shelburne' },
  { id: 84, name: 'St. Catharines' },
  { id: 85, name: 'St. Thomas' },
  { id: 86, name: 'Stratford' },
  { id: 87, name: 'Tecumseh' },
  { id: 88, name: 'Temiskaming Shores (incl. Haileybury, New Liskeard)' },
  { id: 89, name: 'Thorold' },
  { id: 90, name: 'Thunder Bay' },
  { id: 91, name: 'Tillsonburg' },
  { id: 92, name: 'Timmins' },
  { id: 93, name: 'Toronto' },
  { id: 94, name: 'Vaughan' },
  { id: 95, name: 'Wasaga Beach' },
  { id: 96, name: 'Waterloo' },
  { id: 97, name: 'Welland' },
  { id: 98, name: 'Whitby' },
  { id: 99, name: 'Whitchurch - Stouffville' },
  { id: 100, name: 'Windsor' },
  { id: 101, name: 'Woodstock' },
];

export const payment_id = [
  {
    title: "Sautéed Ground Pork over Jasmine Rice",
    p_id: "price_1OQFeDE4gSBdzbVi7QpJUso7",
  },
  {
    title: "French Toast",
    p_id: "price_1OQFfXE4gSBdzbViWoiik9OA",
  },
  {
    title: "Grilled Shrimp",
    p_id: "price_1OQFgaE4gSBdzbViWTrP3ahR",
  },
  {
    title: "Chilly Chicken",
    p_id: "price_1OQFhAE4gSBdzbVi7nb3dqnl",
  },
  {
    title: "Spicy Spaghetti",
    p_id: "price_1OQFiyE4gSBdzbVi4SKB57ZI",
  },
  {
    title: "Black Bean Tostadas",
    p_id: "price_1OQFjXE4gSBdzbViNV0EnCBF",
  },
  {
    title: "Arroz Con Pollo",
    p_id: "price_1OQFkZE4gSBdzbViPYXj7JFg",
  },
  {
    title: "Chicken Alfredo",
    p_id: "price_1OQFlEE4gSBdzbViiO3vCQUs",
  },
  {
    title: "Mango Salsa Salmon",
    p_id: "price_1OQFm6E4gSBdzbViT4NVQFsi",
  },
  {
    title: "Caprese Salad",
    p_id: "price_1OQFnJE4gSBdzbVij1QaVpVE",
  },
  {
    title: "Vegetable Stir-Fry",
    p_id: "price_1OQFoOE4gSBdzbVij9Qc5Gqf",
  },
  {
    title: "Beef Tacos",
    p_id: "price_1OQFpDE4gSBdzbViUMr6Ag3D",
  },
  {
    title: "Penne alla Vodka",
    p_id: "price_1OQFpvE4gSBdzbViVanp4pAv",
  },
  {
    title: "Lobster Bisque",
    p_id: "price_1OQFqmE4gSBdzbVibv6gJLTw",
  },
  {
    title: "Mushroom Risotto",
    p_id: "price_1OQFrTE4gSBdzbViC129hd4Q",
  },
  {
    title: "Eggplant Parmesan",
    p_id: "price_1OQFs5E4gSBdzbVi6t9EqLrO",
  },
  {
    title: "Breakfast Burrito",
    p_id: "price_1OQFspE4gSBdzbViwR8A3vak",
  },
  {
    title: "Pancakes and Bacon",
    p_id: "price_1OQFtWE4gSBdzbViLHyphdsQ",
  },
  {
    title: "Veggie Omelette",
    p_id: "price_1OQFu6E4gSBdzbVivxa9cAkY",
  },
  {
    title: "Greek Yogurt Parfait",
    p_id: "price_1OQFupE4gSBdzbVisXMVmyIW",
  },
];

